version: '3'
services:
  userver-nginx-proxy:
    container_name: userver-nginx-proxy
    restart: unless-stopped
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx/conf.d/
      - ./nginx/logs:/var/log/nginx/
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  userver-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: userver-letsencrypt
    restart: unless-stopped
    depends_on:
      - userver-nginx-proxy
    env_file:
      - letsencrypt/.env
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx/
      - /var/run/docker.sock:/var/run/docker.sock:ro

  userver-monitor:
    container_name: userver-monitor
    restart: unless-stopped
    build:
      context: ./monitor
      dockerfile: Dockerfile
    logging:
      driver: none
    env_file:
      - monitor/.env
    expose:
      - 19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdata-lib:/var/lib/netdata
      - netdata-cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  netdata-lib:
  netdata-cache:
