version: '3'
services:
  userver-nginx-proxy:
    container_name: userver-nginx-proxy
    image: nginxproxy/nginx-proxy:1.2-alpine
    env_file:
      - nginx-proxy/.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx-proxy/conf:/etc/nginx/conf.d/
      - ./nginx-proxy/logs:/var/log/nginx/
      - ./nginx-proxy/nginx.tmpl:/app/nginx.tmpl
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  userver-letsencrypt:
    container_name: userver-letsencrypt
    image: nginxproxy/acme-companion:2.2
    depends_on:
      - userver-nginx-proxy
    env_file:
      - letsencrypt/.env
    volumes:
      - ./certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  userver-monitor:
    container_name: userver-monitor
    image: ferdn4ndo/docker-containers-monitor:1.0.0
    env_file:
      - ./monitor/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  userver-whoami:
    container_name: userver-whoami
    image: traefik/whoami:v1.8
    expose:
      - 80
    env_file:
      - whoami/.env

networks:
  default:
    name: nginx-proxy
    external: true

volumes:
  nginx-vhost:
  nginx-html:
