version: '3'
services:
  # userver-nginx-firewall:
  #   container_name: userver-nginx-firewall
  #   restart: unless-stopped
  #   build:
  #     context: ./nginx-firewall
  #     dockerfile: Dockerfile
  #   env_file:
  #     - nginx-firewall/.env
  #   ports:
  #     - "80:8080"
  #     - "443:8443"
  #   volumes:
  #     - ./certs:/etc/letsencrypt
  #     - ./nginx-firewall/server-confs:/server-confs
  #     - ./nginx-firewall/http-confs:/http-confs
  #     - ./nginx-firewall/hosts.txt:/hosts.txt

  userver-nginx-proxy:
    container_name: userver-nginx-proxy
    restart: unless-stopped
    image: jwilder/nginx-proxy
    env_file:
      - nginx-proxy/.env
    # expose:
    #   - 80
    #   - 443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - ./nginx-proxy/nginx.tmpl:/app/nginx.tmpl
      - ./nginx-proxy/conf:/etc/nginx/conf.d/
      - ./nginx-proxy/logs:/var/log/nginx/
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  userver-letsencrypt:
    container_name: userver-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    depends_on:
      - userver-nginx-proxy
    env_file:
      - letsencrypt/.env
    volumes:
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  userver-whoami:
    container_name: userver-whoami
    restart: unless-stopped
    image: traefik/whoami
    expose:
      - 80
    env_file:
      - whoami/.env

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  netdata-config:
  netdata-lib:
  netdata-cache:
  nginx-vhost:
  nginx-html:
