{{- if .Values.monitor.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "userver-web.fullname" . }}-monitor
  labels:
    {{- include "userver-web.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "userver-web.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: monitor
  template:
    metadata:
      labels:
        {{- include "userver-web.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: monitor
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "userver-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: monitor
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.monitor.image.repository }}:{{ .Values.monitor.image.tag }}"
          imagePullPolicy: {{ .Values.monitor.image.pullPolicy }}
          env:
            - name: VIRTUAL_HOST
              value: {{ include "userver-web.monitorDomain" . }}
            - name: LETSENCRYPT_HOST
              value: {{ include "userver-web.monitorDomain" . }}
            - name: LETSENCRYPT_EMAIL
              value: {{ .Values.letsencrypt.config.email }}
            - name: REFRESH_EVERY_SECONDS
              value: "{{ .Values.monitor.config.refreshEverySeconds }}"
            - name: STATS_FILE
              value: {{ .Values.monitor.config.statsFile }}
            - name: FIFO_PATH
              value: {{ .Values.monitor.config.fifoPath }}
          resources:
            {{- toYaml .Values.monitor.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
