name: Codebase Quality

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs: # Docs: <https://git.io/JvxXE>
  check-codebase-quality:
    name: Check codebase quality with ShellCheck
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run ShellCheck with ReviewDog
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          path: "." # Optional.
          pattern: "*.sh" # Optional.
          exclude: "./.git/*" # Optional.
          check_all_files_with_shebangs: "false" # Optional.
