name: E2E Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs: # Docs: <https://git.io/JvxXE>
  run-ats:
    name: Run the End-to-End (E2E) Automated Tests (AT)
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build and deploy uServer Web services
        uses: ./.github/actions/deploy_local
        with:
          monitor-virtual-host: "monitor.userver.lan"
          whoami-virtual-host: "whoami.userver.lan"

      - name: Run the End-to-End (E2E) tests
        run: ./run_e2e_tests.sh
        shell: bash
